name: Simple Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './...'

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Main Test
        run: go test -coverprofile=coverage1.out -coverpkg=./... -cover ./... && cat coverage1.out | grep -v _mock | grep -v pb.go > cover.out &&go tool cover -func=cover.out